server:
  port: 8081
spring:
  application:
    name: 'order service'

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
